### ISSUE TITLE
ASN.1 Parser V1 Core Features 

### ISSUE THREAD

**Issue by 0xVikasRushi** [zkemail/asn1-parser-circom#4]
# ASN.1 Parser Enhancements

## Tasks:
1. [x] Test date  and date decoding circuits
2. [x] Implement dates circuit 
3. [x] Add octet string support
4. [x] Add bit string support
5. [x] ~~Complete `AsnParser` circuit~~ (since most all params included in `AsnStartAndEndIndex`) 
6. [x] Add Signature and Signature algorithm in `AsnParser`
7. [x] add number of constraints in readme
8. [x] Release as npm package 
9. [x] Create demo website (in separate repo)
